options:
  env:
    - WORKSPACE_ROOT=/workspace

steps:
  - name: 'gcr.io/cloud-builders/bash'
    id: 'PHASE 1: preflight'
    entrypoint: 'bash'
    args:
      - -ceu
      - |
        set -euo pipefail
        echo "===== PHASE 1: preflight ====="
        echo "BUILD_ID=${BUILD_ID}"
        echo "PROJECT_ID=${PROJECT_ID}"
        echo "SHORT_SHA=${SHORT_SHA}"
        echo "COMMIT_SHA=${COMMIT_SHA}"
        echo "TAG=${_TAG}"

  - name: 'gcr.io/cloud-builders/bash'
    id: 'PHASE 2: safety guard'
    waitFor: ['PHASE 1: preflight']
    entrypoint: 'bash'
    args:
      - -ceu
      - |
        set -euo pipefail
        echo "===== PHASE 2: safety guard ====="

        echo "--- Checking for ':latest' image tags ---"
        # RISK: Depends on core utilities existing in the container (`find`, `grep`, `xargs`). If the `bash` image lacks these, this will fail immediately.
        # RISK: `find . -name "*.yaml" -o -name "*.yml"` has no parentheses and no `-type f`; it may emit directories or unexpected matches in edge cases.
        # RISK: `grep -v "cloudbuild"` filters by substring anywhere in the path; it may exclude more than intended if a directory/file contains "cloudbuild".
        # RISK: `xargs grep ...` with *no input* can invoke `grep` with no args (exit 2). In bash, failures inside `if <pipeline>; then` don't trip `set -e`,
        #       so this can silently turn the check into a no-op while still emitting confusing stderr.
        if find . -name "*.yaml" -o -name "*.yml" | grep -v "cloudbuild" | xargs grep -q "image:.*:latest"; then
          echo "❌ FAILED: Use of ':latest' image tag is forbidden."
          exit 1
        else
          echo "✅ PASSED: No ':latest' image tags found."
        fi

        echo "--- Checking for 'AGENT_MODE=EXECUTE' ---"
        AGENT_MODE_EXECUTE_FOUND=0
        find "${WORKSPACE_ROOT}" -name "*.yaml" -o -name "*.yml" -o -name "*.py" -o -name "*.sh" -o -name "Dockerfile" | grep -v "cloudbuild" | while read FILE_VAR;
        do
          # RISK: The `while ...; do ... done` is fed by a pipeline, so in bash it runs in a subshell.
          #       Any changes to `AGENT_MODE_EXECUTE_FOUND` inside the loop will *not* propagate to the parent shell,
          #       making the post-loop `if [ "$$AGENT_MODE_EXECUTE_FOUND" -eq 1 ]` check ineffective.
          #       (This is more of a safety-gap than an early-failure cause, but it can hide real violations.)
          if [ -f "$$FILE_VAR" ]; then
            while read LINE_VAR;
            do
              # Check for literal 'AGENT_MODE=EXECUTE' or 'AGENT_MODE: EXECUTE'
              if echo "$$LINE_VAR" | grep -q "AGENT_MODE=EXECUTE" || echo "$$LINE_VAR" | grep -q "AGENT_MODE: EXECUTE"; then
                # Exclude the ALLOWED_AGENT_MODES definition itself
                if ! echo "$$LINE_VAR" | grep -q "ALLOWED_AGENT_MODES"; then
                  echo "❌ FAILED: AGENT_MODE must not be set to EXECUTE in committed code."
                  echo "   File: $$FILE_VAR"
                  echo "   Line: $$LINE_VAR"
                  AGENT_MODE_EXECUTE_FOUND=1
                  break # Exit inner loop
                fi
              fi
            done < "$$FILE_VAR"
          fi
          if [ "$$AGENT_MODE_EXECUTE_FOUND" -eq 1 ]; then
            break # Exit outer loop
          fi
        done

        if [ "$$AGENT_MODE_EXECUTE_FOUND" -eq 1 ]; then
          exit 1
        else
          echo "✅ PASSED: No instances of 'AGENT_MODE=EXECUTE' found."
        fi

        echo "--- Checking for scaled execution agents (replicas > 0) ---"
        # RISK: Repo currently has no `./k8s/execution/` directory, so `find` will emit "No such file or directory" on stderr and return nonzero.
        #       In an `if` condition, bash won't exit on that despite `set -e`, so this check becomes a no-op (and can look like a failure in logs).
        # RISK: Same `xargs` empty-input caveat as above.
        if find ./k8s/execution -name "*.yaml" -o -name "*.yml" | xargs grep -q "replicas:[[:space:]]*[1-9]"; then
          echo "❌ FAILED: Execution agent replicas must be 0 in committed code."
          exit 1
        else
          echo "✅ PASSED: No execution agents found with replicas > 0."
        fi

  - name: 'gcr.io/cloud-builders/bash'
    id: 'PHASE 4: docker build'
    waitFor: ['PHASE 2: safety guard']
    entrypoint: 'bash'
    args:
      - -ceu
      - |
        set -euo pipefail
        echo "===== PHASE 4: docker build ====="

  # Build and push marketdata-mcp-server
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Build marketdata-mcp-server'
    waitFor: ['PHASE 4: docker build']
    entrypoint: 'bash'
    args:
      - -ceu
      - |
        set -euo pipefail
        IMAGE_TAG="${_REGION}-docker.pkg.dev/${_PROJECT}/${_REPO}/marketdata-mcp-server:${_TAG}"
        echo "docker build tag=${IMAGE_TAG}"
        docker build -t "${IMAGE_TAG}" -f backend/Dockerfile.marketdata-mcp-server .

  - name: 'gcr.io/cloud-builders/bash'
    id: 'PHASE 3: import smoke'
    waitFor: ['Build marketdata-mcp-server']
    entrypoint: 'bash'
    args:
      - -ceu
      - |
        set -euo pipefail
        echo "===== PHASE 3: import smoke ====="

  - name: 'gcr.io/cloud-builders/bash'
    id: 'Import gate marketdata-mcp-server'
    waitFor: ['PHASE 3: import smoke']
    entrypoint: 'bash'
    args:
      - "-c"
      - |
        set -euo pipefail
        IMAGE_REF='${_REGION}-docker.pkg.dev/${_PROJECT}/${_REPO}/marketdata-mcp-server:${_TAG}'
        chmod +x ./scripts/ci_import_gate.sh
        ./scripts/ci_import_gate.sh "${IMAGE_REF}" backend.app

  # Build and push strategy-engine
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Build strategy-engine'
    waitFor: ['Import gate marketdata-mcp-server']
    entrypoint: 'bash'
    args:
      - -ceu
      - |
        set -euo pipefail
        IMAGE_TAG="${_REGION}-docker.pkg.dev/${_PROJECT}/${_REPO}/strategy-engine:${_TAG}"
        echo "docker build tag=${IMAGE_TAG}"
        docker build -t "${IMAGE_TAG}" -f infra/Dockerfile.strategy_engine .

  - name: 'gcr.io/cloud-builders/bash'
    id: 'Import gate strategy-engine'
    waitFor: ['Build strategy-engine']
    entrypoint: 'bash'
    args:
      - "-c"
      - |
        set -euo pipefail
        IMAGE_REF='${_REGION}-docker.pkg.dev/${_PROJECT}/${_REPO}/strategy-engine:${_TAG}'
        chmod +x ./scripts/ci_import_gate.sh
        ./scripts/ci_import_gate.sh "${IMAGE_REF}" backend.strategy_engine.service

  # Build and push strategy-runtime (used by gamma and whale strategies)
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Build strategy-runtime'
    waitFor: ['Import gate strategy-engine']
    entrypoint: 'bash'
    args:
      - -ceu
      - |
        set -euo pipefail
        IMAGE_TAG="${_REGION}-docker.pkg.dev/${_PROJECT}/${_REPO}/strategy-runtime:${_TAG}"
        echo "docker build tag=${IMAGE_TAG}"
        docker build -t "${IMAGE_TAG}" -f backend/strategy_service/Dockerfile .

  - name: 'gcr.io/cloud-builders/bash'
    id: 'Import gate strategy-runtime'
    waitFor: ['Build strategy-runtime']
    entrypoint: 'bash'
    args:
      - "-c"
      - |
        set -euo pipefail
        IMAGE_REF='${_REGION}-docker.pkg.dev/${_PROJECT}/${_REPO}/strategy-runtime:${_TAG}'
        sh ./scripts/ci_import_gate.sh "${IMAGE_REF}" backend.strategy_service.app

  - name: 'gcr.io/cloud-builders/bash'
    id: 'PHASE 5: docker push'
    waitFor: ['Import gate strategy-runtime']
    entrypoint: 'bash'
    args:
      - -ceu
      - |
        set -euo pipefail
        echo "===== PHASE 5: docker push ====="

  - name: 'gcr.io/cloud-builders/docker'
    id: 'Push marketdata-mcp-server'
    waitFor: ['PHASE 5: docker push']
    entrypoint: 'bash'
    args:
      - -ceu
      - |
        set -euo pipefail
        IMAGE_TAG="${_REGION}-docker.pkg.dev/${_PROJECT}/${_REPO}/marketdata-mcp-server:${_TAG}"
        docker push "${IMAGE_TAG}"

  - name: 'gcr.io/cloud-builders/docker'
    id: 'Push strategy-engine'
    waitFor: ['Push marketdata-mcp-server']
    entrypoint: 'bash'
    args:
      - -ceu
      - |
        set -euo pipefail
        IMAGE_TAG="${_REGION}-docker.pkg.dev/${_PROJECT}/${_REPO}/strategy-engine:${_TAG}"
        docker push "${IMAGE_TAG}"

  - name: 'gcr.io/cloud-builders/docker'
    id: 'Push strategy-runtime'
    waitFor: ['Push strategy-engine']
    entrypoint: 'bash'
    args:
      - -ceu
      - |
        set -euo pipefail
        IMAGE_TAG="${_REGION}-docker.pkg.dev/${_PROJECT}/${_REPO}/strategy-runtime:${_TAG}"
        docker push "${IMAGE_TAG}"
