steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'build',
    '-t', 'us-east4-docker.pkg.dev/agenttrader-prod/trader-repo/marketdata-mcp-server:$SHORT_SHA',
    '-f', 'backend/Dockerfile.marketdata-mcp-server',
    '.'
  ]
images:
- 'us-east4-docker.pkg.dev/agenttrader-prod/trader-repo/marketdata-mcp-server:$SHORT_SHA'
