# This CI pipeline enforces institutional safety guarantees.
steps:
  - name: gcr.io/cloud-builders/gcloud
    id: preflight
    entrypoint: bash
    args:
      - -ceu
      - |
        set -euo pipefail
        pwd
        ls -la
        ls -la /workspace
        ls -la /workspace/scripts || true
        echo "BRANCH=$BRANCH_NAME COMMIT=$COMMIT_SHA" || true

  - name: gcr.io/cloud-builders/gcloud
    id: Safety Guard
    entrypoint: bash
    args:
      - '-c'
      - |
        set -euo pipefail
        test -f /workspace/scripts/ci_safety_guard.sh
        ls -la /workspace/scripts/ci_safety_guard.sh
        chmod +x /workspace/scripts/ci_safety_guard.sh
        /workspace/scripts/ci_safety_guard.sh
        echo "✅ SAFETY GUARD PASS"

        echo "CI SAFETY GUARD PASSED — proceeding to build"

  # c) Import smoke check (source-based; fail fast before image builds).
  #
  # We intentionally install from a pinned lock file for deterministic results.
  # The smoke check here is scoped to the entrypoints built in this pipeline.
  - name: 'python:3.12-slim'
    id: 'Import smoke check'
    waitFor: ['Safety Guard']
    entrypoint: 'bash'
    args:
      - -ceu
      - |
        echo "================================================================"
        echo "PHASE 3: import smoke"
        echo "================================================================"
        echo "--- Import smoke check (source) ---"
        python -V
        python -m pip --version || python -m ensurepip
        python -m pip install --no-cache-dir --upgrade pip
        python -m pip install --no-cache-dir -r backend/strategy_service/requirements.lock
        python ./scripts/smoke_check_imports.py \
          --no-defaults \
          --module backend.app \
          --module backend.strategy_engine.service \
          --module backend.strategy_service.app

  # d) Docker build(s) (serialized; each build is immediately gated).
  #
  # NOTE: The "import gate" runs inside the built image (docker run) to validate
  # runtime imports using the image's own dependency set.

  - name: 'gcr.io/cloud-builders/bash'
    id: 'PHASE 4: docker build'
    waitFor: ['Import smoke check']
    entrypoint: 'bash'
    args:
      - -ceu
      - |
        echo "================================================================"
        echo "PHASE 4: docker build"
        echo "================================================================"

  # Build marketdata-mcp-server
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Build marketdata-mcp-server'
    waitFor: ['PHASE 4: docker build']
    args: [
      'build',
      '-t', '${_REGION}-docker.pkg.dev/${_PROJECT}/${_REPO}/marketdata-mcp-server:${_TAG}',
      '-f', '/workspace/backend/Dockerfile.marketdata-mcp-server',
      '/workspace'
    ]

  - name: 'gcr.io/cloud-builders/bash'
    id: 'Import gate marketdata-mcp-server'
    waitFor: ['Build marketdata-mcp-server']
    entrypoint: 'bash'
    args:
      - build
      - -t
      - ${_REGION}-docker.pkg.dev/${_PROJECT}/${_REPO}/strategy-engine:${_TAG}
      - -f
      - infra/Dockerfile.strategy_engine
      - .

  - id: Push strategy-engine
    name: gcr.io/cloud-builders/docker
    args:
      - push
      - ${_REGION}-docker.pkg.dev/${_PROJECT}/${_REPO}/strategy-engine:${_TAG}

  # ------------------------------------------------------------
  # PHASE 3: BUILD MARKETDATA MCP SERVER
  # ------------------------------------------------------------
  - id: Build marketdata-mcp-server
    name: gcr.io/cloud-builders/docker
    args:
      - "-c"
      - |
        set -euo pipefail
        IMAGE_REF='${_REGION}-docker.pkg.dev/${_PROJECT}/${_REPO}/strategy-runtime:${_TAG}'
        sh ./scripts/ci_import_gate.sh "${IMAGE_REF}" backend.strategy_service.app

  # e) Docker push(es) (serialized; publish only after all gates pass).
  - name: 'gcr.io/cloud-builders/bash'
    id: 'PHASE 5: docker push'
    waitFor: ['Import gate strategy-runtime']
    entrypoint: 'bash'
    args:
      - -ceu
      - |
        echo "================================================================"
        echo "PHASE 5: docker push"
        echo "================================================================"

  - name: 'gcr.io/cloud-builders/docker'
    id: 'Push marketdata-mcp-server'
    waitFor: ['PHASE 5: docker push']
    args: [
      'push',
      '${_REGION}-docker.pkg.dev/${_PROJECT}/${_REPO}/marketdata-mcp-server:${_TAG}'
    ]

  - name: 'gcr.io/cloud-builders/docker'
    id: 'Push strategy-engine'
    waitFor: ['Push marketdata-mcp-server']
    args: [
      'push',
      '${_REGION}-docker.pkg.dev/${_PROJECT}/${_REPO}/strategy-engine:${_TAG}'
    ]

images:
  - ${_REGION}-docker.pkg.dev/${_PROJECT}/${_REPO}/strategy-engine:${_TAG}
  - ${_REGION}-docker.pkg.dev/${_PROJECT}/${_REPO}/marketdata-mcp-server:${_TAG}
