steps:
  - name: 'bash'
    id: 'Safety Guard'
    entrypoint: '/bin/sh'
    args:
      - '-c'
      - './scripts/ci_safety_guard.sh'
- name: gcr.io/cloud-builders/bash
  entrypoint: bash
  args:
    [
      "build",
      "-f",
      "backend/strategy_service/Dockerfile",
      "-t",
      "${_REGION}-docker.pkg.dev/${_PROJECT}/${_REPO}/strategy-runtime:${_TAG}",
      ".",
    ]
images:
- "${_REGION}-docker.pkg.dev/${_PROJECT}/${_REPO}/strategy-runtime:${_TAG}"