# This CI pipeline enforces institutional safety guarantees.
steps:
  # NOTE ON ORDER (determinism + debuggability):
  # - Checkout first so every later step can log the same source state.
  # - Safety guard next to fail fast on forbidden config / dangerous settings.
  # - Import smoke check next to fail fast on broken Python entrypoints *before*
  #   spending time building images.
  # - Docker builds are serialized (explicit waitFor chain) to avoid hidden
  #   parallelism and to make failures reproducible and logs easier to read.
  # - Docker pushes are last so nothing is published unless all gates pass.

  # a) Checkout
  - name: 'gcr.io/cloud-builders/git'
    id: 'Checkout'
    entrypoint: 'bash'
    args:
      - -c
      - |
        set -euo pipefail
        echo "--- Checkout / source context ---"
        echo "PWD=$$(pwd)"
        echo "Workspace contents:"
        ls -la
        if [ -d .git ]; then
          echo "GIT_SHA=$$(git rev-parse HEAD)"
          echo "GIT_STATUS_PORCELAIN:"
          git status --porcelain || true
        else
          echo "INFO: .git directory not present (source may be provided as an archive)."
        fi

  # b) Safety guard
  - name: 'gcr.io/cloud-builders/bash'
    id: 'CI Layout Validate'
    waitFor: ['Checkout']
    entrypoint: 'bash'
    args:
      - -c
      - |
        set -euo pipefail
        bash ./scripts/validate_ci_layout.sh

  - name: 'gcr.io/cloud-builders/bash'
    id: 'Safety Guard'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        set -euo pipefail
        echo "--- Safety Guard preflight ---"
        chmod +x ./scripts/ci_safety_guard.sh
        ./scripts/ci_safety_guard.sh
    waitFor: ['CI Layout Validate']

  # c) Import smoke check (source-based; fail fast before image builds).
  #
  # We intentionally install from a pinned lock file for deterministic results.
  # The smoke check here is scoped to the entrypoints built in this pipeline.
  - name: 'python:3.12-slim'
    id: 'Import smoke check'
    waitFor: ['Safety Guard']
    entrypoint: 'bash'
    args:
      - -c
      - |
        set -euo pipefail
        echo "--- Import smoke check (source) ---"
        python -V
        python -m pip --version || python -m ensurepip
        python -m pip install --no-cache-dir --upgrade pip
        python -m pip install --no-cache-dir -r backend/strategy_service/requirements.lock
        python ./scripts/smoke_check_imports.py \
          --no-defaults \
          --module backend.app \
          --module backend.strategy_engine.service \
          --module backend.strategy_service.app

  # d) Docker build(s) (serialized; each build is immediately gated).
  #
  # NOTE: The "import gate" runs inside the built image (docker run) to validate
  # runtime imports using the image's own dependency set.

  # Build marketdata-mcp-server
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Build marketdata-mcp-server'
    waitFor: ['Import smoke check']
    args: [
      'build',
      '-t', '${_REGION}-docker.pkg.dev/${_PROJECT}/${_REPO}/marketdata-mcp-server:${_TAG}',
      '-f', '/workspace/backend/Dockerfile.marketdata-mcp-server',
      '/workspace'
    ]

  - name: 'gcr.io/cloud-builders/bash'
    id: 'Import gate marketdata-mcp-server'
    waitFor: ['Build marketdata-mcp-server']
    entrypoint: 'bash'
    args:
      - "-c"
      - |
        set -euo pipefail
        IMAGE_REF='${_REGION}-docker.pkg.dev/${_PROJECT}/${_REPO}/marketdata-mcp-server:${_TAG}'
        chmod +x ./scripts/ci_import_gate.sh
        ./scripts/ci_import_gate.sh "${IMAGE_REF}" backend.app

  # Build strategy-engine
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Build strategy-engine'
    waitFor: ['Import gate marketdata-mcp-server']
    args: [
      'build',
      '-t', '${_REGION}-docker.pkg.dev/${_PROJECT}/${_REPO}/strategy-engine:${_TAG}',
      '-f', '/workspace/infra/Dockerfile.strategy_engine',
      '/workspace'
    ]

  - name: 'gcr.io/cloud-builders/bash'
    id: 'Import gate strategy-engine'
    waitFor: ['Build strategy-engine']
    entrypoint: 'bash'
    args:
      - "-c"
      - |
        set -euo pipefail
        IMAGE_REF='${_REGION}-docker.pkg.dev/${_PROJECT}/${_REPO}/strategy-engine:${_TAG}'
        chmod +x ./scripts/ci_import_gate.sh
        ./scripts/ci_import_gate.sh "${IMAGE_REF}" backend.strategy_engine.service

  # Build strategy-runtime (used by gamma and whale strategies)
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Build strategy-runtime'
    waitFor: ['Import gate strategy-engine']
    args: [
      'build',
      '-t', '${_REGION}-docker.pkg.dev/${_PROJECT}/${_REPO}/strategy-runtime:${_TAG}',
      '-f', '/workspace/backend/strategy_service/Dockerfile',
      '/workspace'
    ]

  - name: 'gcr.io/cloud-builders/bash'
    id: 'Import gate strategy-runtime'
    waitFor: ['Build strategy-runtime']
    entrypoint: 'bash'
    args:
      - "-c"
      - |
        set -euo pipefail
        IMAGE_REF='${_REGION}-docker.pkg.dev/${_PROJECT}/${_REPO}/strategy-runtime:${_TAG}'
        sh ./scripts/ci_import_gate.sh "${IMAGE_REF}" backend.strategy_service.app

  # e) Docker push(es) (serialized; publish only after all gates pass).
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Push marketdata-mcp-server'
    waitFor: ['Import gate strategy-runtime']
    args: [
      'push',
      '${_REGION}-docker.pkg.dev/${_PROJECT}/${_REPO}/marketdata-mcp-server:${_TAG}'
    ]

  - name: 'gcr.io/cloud-builders/docker'
    id: 'Push strategy-engine'
    waitFor: ['Push marketdata-mcp-server']
    args: [
      'push',
      '${_REGION}-docker.pkg.dev/${_PROJECT}/${_REPO}/strategy-engine:${_TAG}'
    ]

  - name: 'gcr.io/cloud-builders/docker'
    id: 'Push strategy-runtime'
    waitFor: ['Push strategy-engine']
    args: [
      'push',
      '${_REGION}-docker.pkg.dev/${_PROJECT}/${_REPO}/strategy-runtime:${_TAG}'
    ]
