steps:
- name: gcr.io/cloud-builders/bash
  entrypoint: bash
  args:
    [
      "build",
      "-f",
      "infra/Dockerfile.strategy_engine",
      "-t",
      "us-east4-docker.pkg.dev/agenttrader-prod/trader-repo/strategy-engine:${SHORT_SHA}",
      ".",
    ]
images:
- "us-east4-docker.pkg.dev/agenttrader-prod/trader-repo/strategy-engine:${SHORT_SHA}"
