options:
  env:
    - WORKSPACE_ROOT=/workspace

steps:
  - name: 'bash'
    id: 'Safety Guard'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        set -e
        echo "--- Checking for ':latest' image tags ---"
        LATEST_MATCH="$(find . -name "*.yaml" -o -name "*.yml" | grep -v "cloudbuild" | xargs grep -nH "image:.*:latest" 2>/dev/null | head -n 1 || true)"
        if [ -n "$$LATEST_MATCH" ]; then
          echo "CI SAFETY GUARD FAILED"
          echo "Rule: No ':latest' image tags"
          echo "Triggered by: $$LATEST_MATCH"
          echo "Remediation: Pin images to immutable versions (e.g., ':1.2.3') or digests (e.g., '@sha256:...')."
          exit 1
        else
          echo "✅ PASSED: No ':latest' image tags found."
        fi

        echo "--- Checking for 'AGENT_MODE=EXECUTE' ---"
        AGENT_MODE_EXECUTE_FOUND=0
        find "${WORKSPACE_ROOT}" -name "*.yaml" -o -name "*.yml" -o -name "*.py" -o -name "*.sh" -o -name "Dockerfile" | grep -v "cloudbuild" | while read FILE_VAR;
        do
          if [ -f "$$FILE_VAR" ]; then
            while read LINE_VAR;
            do
              # Check for literal 'AGENT_MODE=EXECUTE' or 'AGENT_MODE: EXECUTE'
              if echo "$$LINE_VAR" | grep -q "AGENT_MODE=EXECUTE" || echo "$$LINE_VAR" | grep -q "AGENT_MODE: EXECUTE"; then
                # Exclude the ALLOWED_AGENT_MODES definition itself
                if ! echo "$$LINE_VAR" | grep -q "ALLOWED_AGENT_MODES"; then
                  echo "CI SAFETY GUARD FAILED"
                  echo "Rule: AGENT_MODE must not be set to EXECUTE in committed code"
                  echo "Triggered by file: $$FILE_VAR"
                  echo "Triggered by line: $$LINE_VAR"
                  echo "Remediation: Remove the setting or change it to a non-executing mode; enforce EXECUTE only via runtime configuration/secrets, never committed code."
                  AGENT_MODE_EXECUTE_FOUND=1
                  break # Exit inner loop
                fi
              fi
            done < "$$FILE_VAR"
          fi
          if [ "$$AGENT_MODE_EXECUTE_FOUND" -eq 1 ]; then
            break # Exit outer loop
          fi
        done

        if [ "$$AGENT_MODE_EXECUTE_FOUND" -eq 1 ]; then
          exit 1
        else
          echo "✅ PASSED: No instances of 'AGENT_MODE=EXECUTE' found."
        fi

        echo "--- Checking for scaled execution agents (replicas > 0) ---"
        REPLICAS_MATCH="$(find ./k8s/execution -name "*.yaml" -o -name "*.yml" | xargs grep -nH "replicas:[[:space:]]*[1-9]" 2>/dev/null | head -n 1 || true)"
        if [ -n "$$REPLICAS_MATCH" ]; then
          echo "CI SAFETY GUARD FAILED"
          echo "Rule: Execution agent replicas must be 0 in committed code"
          echo "Triggered by: $$REPLICAS_MATCH"
          echo "Remediation: Set 'replicas: 0' in committed manifests; scale up only via approved runtime overrides (e.g., kubectl/Helm/Kustomize) during controlled operations."
          exit 1
        else
          echo "✅ PASSED: No execution agents found with replicas > 0."
        fi

        echo "CI SAFETY GUARD PASSED — proceeding to build"

  # Build and push marketdata-mcp-server
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Build marketdata-mcp-server'
    args: [
      'build',
      '-t', '${_REGION}-docker.pkg.dev/${_PROJECT}/${_REPO}/marketdata-mcp-server:${_TAG}',
      '-f', '/workspace/backend/Dockerfile.marketdata-mcp-server',
      '/workspace'
    ]

  - name: 'gcr.io/cloud-builders/bash'
    id: 'Import gate marketdata-mcp-server'
    entrypoint: 'bash'
    args:
      - -ceu
      - |
        IMAGE_REF='${_REGION}-docker.pkg.dev/${_PROJECT}/${_REPO}/marketdata-mcp-server:${_TAG}'
        sh "${WORKSPACE_ROOT}/scripts/ci_import_gate.sh" "${IMAGE_REF}" backend.app

  # Build and push strategy-engine
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Build strategy-engine'
    args: [
      'build',
      '-t', '${_REGION}-docker.pkg.dev/${_PROJECT}/${_REPO}/strategy-engine:${_TAG}',
      '-f', '/workspace/infra/Dockerfile.strategy_engine',
      '/workspace'
    ]

  - name: 'gcr.io/cloud-builders/bash'
    id: 'Import gate strategy-engine'
    entrypoint: 'bash'
    args:
      - -ceu
      - |
        IMAGE_REF='${_REGION}-docker.pkg.dev/${_PROJECT}/${_REPO}/strategy-engine:${_TAG}'
        sh "${WORKSPACE_ROOT}/scripts/ci_import_gate.sh" "${IMAGE_REF}" backend.strategy_engine.service

  # Build and push strategy-runtime (used by gamma and whale strategies)
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Build strategy-runtime'
    args: [
      'build',
      '-t', '${_REGION}-docker.pkg.dev/${_PROJECT}/${_REPO}/strategy-runtime:${_TAG}',
      '-f', '/workspace/backend/strategy_service/Dockerfile',
      '/workspace'
    ]

  - name: 'gcr.io/cloud-builders/bash'
    id: 'Import gate strategy-runtime'
    entrypoint: 'bash'
    args:
      - -ceu
      - |
        IMAGE_REF='${_REGION}-docker.pkg.dev/${_PROJECT}/${_REPO}/strategy-runtime:${_TAG}'
        sh "${WORKSPACE_ROOT}/scripts/ci_import_gate.sh" "${IMAGE_REF}" backend.strategy_service.app
