options:
  env:
    - WORKSPACE_ROOT=/workspace

steps:
  - name: 'gcr.io/cloud-builders/bash'
    id: 'PHASE 1: preflight'
    entrypoint: 'bash'
    args:
      - -ceu
      - |
        set -euo pipefail
        echo "===== PHASE 1: preflight ====="
        echo "BUILD_ID=${BUILD_ID}"
        echo "PROJECT_ID=${PROJECT_ID}"
        echo "SHORT_SHA=${SHORT_SHA}"
        echo "COMMIT_SHA=${COMMIT_SHA}"
        echo "TAG=${_TAG}"

  - name: 'gcr.io/cloud-builders/bash'
    id: 'PHASE 2: safety guard'
    waitFor: ['PHASE 1: preflight']
    entrypoint: 'bash'
    args:
      - -ceu
      - |
        set -euo pipefail
        echo "===== PHASE 2: safety guard ====="

        echo "--- Checking for ':latest' image tags ---"
        if find "${WORKSPACE_ROOT}" -name "*.yaml" -o -name "*.yml" | grep -v "cloudbuild" | xargs grep -q "image:.*:latest"; then
          echo "❌ FAILED: Use of ':latest' image tag is forbidden."
          exit 1
        else
          echo "✅ PASSED: No ':latest' image tags found."
        fi

        echo "--- Checking for 'AGENT_MODE=EXECUTE' ---"
        AGENT_MODE_EXECUTE_FOUND=0
        find "${WORKSPACE_ROOT}" -name "*.yaml" -o -name "*.yml" -o -name "*.py" -o -name "*.sh" -o -name "Dockerfile" | grep -v "cloudbuild" | while read FILE_VAR;
        do
          if [ -f "$$FILE_VAR" ]; then
            while read LINE_VAR;
            do
              # Check for literal 'AGENT_MODE=EXECUTE' or 'AGENT_MODE: EXECUTE'
              if echo "$$LINE_VAR" | grep -q "AGENT_MODE=EXECUTE" || echo "$$LINE_VAR" | grep -q "AGENT_MODE: EXECUTE"; then
                # Exclude the ALLOWED_AGENT_MODES definition itself
                if ! echo "$$LINE_VAR" | grep -q "ALLOWED_AGENT_MODES"; then
                  echo "❌ FAILED: AGENT_MODE must not be set to EXECUTE in committed code."
                  echo "   File: $$FILE_VAR"
                  echo "   Line: $$LINE_VAR"
                  AGENT_MODE_EXECUTE_FOUND=1
                  break # Exit inner loop
                fi
              fi
            done < "$$FILE_VAR"
          fi
          if [ "$$AGENT_MODE_EXECUTE_FOUND" -eq 1 ]; then
            break # Exit outer loop
          fi
        done

        if [ "$$AGENT_MODE_EXECUTE_FOUND" -eq 1 ]; then
          exit 1
        else
          echo "✅ PASSED: No instances of 'AGENT_MODE=EXECUTE' found."
        fi

        echo "--- Checking for scaled execution agents (replicas > 0) ---"
        if find "${WORKSPACE_ROOT}/k8s/execution" -name "*.yaml" -o -name "*.yml" | xargs grep -q "replicas:[[:space:]]*[1-9]"; then
          echo "❌ FAILED: Execution agent replicas must be 0 in committed code."
          exit 1
        else
          echo "✅ PASSED: No execution agents found with replicas > 0."
        fi

  - name: 'gcr.io/cloud-builders/bash'
    id: 'PHASE 4: docker build'
    waitFor: ['PHASE 2: safety guard']
    entrypoint: 'bash'
    args:
      - -ceu
      - |
        set -euo pipefail
        echo "===== PHASE 4: docker build ====="

  # Build and push marketdata-mcp-server
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Build marketdata-mcp-server'
    waitFor: ['PHASE 4: docker build']
    entrypoint: 'bash'
    args:
      - -ceu
      - |
        set -euo pipefail
        IMAGE_TAG="${_REGION}-docker.pkg.dev/${_PROJECT}/${_REPO}/marketdata-mcp-server:${_TAG}"
        echo "docker build tag=${IMAGE_TAG}"
        docker build -t "${IMAGE_TAG}" -f backend/Dockerfile.marketdata-mcp-server .

  - name: 'gcr.io/cloud-builders/bash'
    id: 'PHASE 3: import smoke'
    waitFor: ['Build marketdata-mcp-server']
    entrypoint: 'bash'
    args:
      - -ceu
      - |
        set -euo pipefail
        echo "===== PHASE 3: import smoke ====="

  - name: 'gcr.io/cloud-builders/bash'
    id: 'Import gate marketdata-mcp-server'
    waitFor: ['PHASE 3: import smoke']
    entrypoint: 'bash'
    args:
      - -ceu
      - |
        IMAGE_REF='${_REGION}-docker.pkg.dev/${_PROJECT}/${_REPO}/marketdata-mcp-server:${_TAG}'
        sh "${WORKSPACE_ROOT}/scripts/ci_import_gate.sh" "${IMAGE_REF}" backend.app

  # Build and push strategy-engine
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Build strategy-engine'
    waitFor: ['Import gate marketdata-mcp-server']
    entrypoint: 'bash'
    args:
      - -ceu
      - |
        set -euo pipefail
        IMAGE_TAG="${_REGION}-docker.pkg.dev/${_PROJECT}/${_REPO}/strategy-engine:${_TAG}"
        echo "docker build tag=${IMAGE_TAG}"
        docker build -t "${IMAGE_TAG}" -f infra/Dockerfile.strategy_engine .

  - name: 'gcr.io/cloud-builders/bash'
    id: 'Import gate strategy-engine'
    waitFor: ['Build strategy-engine']
    entrypoint: 'bash'
    args:
      - -ceu
      - |
        IMAGE_REF='${_REGION}-docker.pkg.dev/${_PROJECT}/${_REPO}/strategy-engine:${_TAG}'
        sh "${WORKSPACE_ROOT}/scripts/ci_import_gate.sh" "${IMAGE_REF}" backend.strategy_engine.service

  # Build and push strategy-runtime (used by gamma and whale strategies)
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Build strategy-runtime'
    waitFor: ['Import gate strategy-engine']
    entrypoint: 'bash'
    args:
      - -ceu
      - |
        set -euo pipefail
        IMAGE_TAG="${_REGION}-docker.pkg.dev/${_PROJECT}/${_REPO}/strategy-runtime:${_TAG}"
        echo "docker build tag=${IMAGE_TAG}"
        docker build -t "${IMAGE_TAG}" -f backend/strategy_service/Dockerfile .

  - name: 'gcr.io/cloud-builders/bash'
    id: 'Import gate strategy-runtime'
    waitFor: ['Build strategy-runtime']
    entrypoint: 'bash'
    args:
      - -ceu
      - |
        IMAGE_REF='${_REGION}-docker.pkg.dev/${_PROJECT}/${_REPO}/strategy-runtime:${_TAG}'
        sh ./scripts/ci_import_gate.sh "${IMAGE_REF}" backend.strategy_service.app

  - name: 'gcr.io/cloud-builders/bash'
    id: 'PHASE 5: docker push'
    waitFor: ['Import gate strategy-runtime']
    entrypoint: 'bash'
    args:
      - -ceu
      - |
        set -euo pipefail
        echo "===== PHASE 5: docker push ====="

  - name: 'gcr.io/cloud-builders/docker'
    id: 'Push marketdata-mcp-server'
    waitFor: ['PHASE 5: docker push']
    entrypoint: 'bash'
    args:
      - -ceu
      - |
        set -euo pipefail
        IMAGE_TAG="${_REGION}-docker.pkg.dev/${_PROJECT}/${_REPO}/marketdata-mcp-server:${_TAG}"
        docker push "${IMAGE_TAG}"

  - name: 'gcr.io/cloud-builders/docker'
    id: 'Push strategy-engine'
    waitFor: ['Push marketdata-mcp-server']
    entrypoint: 'bash'
    args:
      - -ceu
      - |
        set -euo pipefail
        IMAGE_TAG="${_REGION}-docker.pkg.dev/${_PROJECT}/${_REPO}/strategy-engine:${_TAG}"
        docker push "${IMAGE_TAG}"

  - name: 'gcr.io/cloud-builders/docker'
    id: 'Push strategy-runtime'
    waitFor: ['Push strategy-engine']
    entrypoint: 'bash'
    args:
      - -ceu
      - |
        set -euo pipefail
        IMAGE_TAG="${_REGION}-docker.pkg.dev/${_PROJECT}/${_REPO}/strategy-runtime:${_TAG}"
        docker push "${IMAGE_TAG}"
