# This CI pipeline enforces institutional safety guarantees.
steps:
  # Diagnostic step (runs before anything else) to make early failures self-explanatory.
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'Diagnostics (pre-build)'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        set -e
        pwd
        ls -la
        ls -la scripts/ || true
        git rev-parse --short HEAD || true
        echo $BRANCH_NAME $COMMIT_SHA || true

  # Copy guard script to a deterministic location (idempotent).
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'Copy CI safety guard'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        set -e
        mkdir -p /workspace/.cloudbuild
        cp -f /workspace/scripts/ci_safety_guard.sh /workspace/.cloudbuild/ci_safety_guard.sh
        ls -la /workspace/.cloudbuild
        ls -la /workspace/.cloudbuild/ci_safety_guard.sh

  # Safety guard MUST pass before any docker build/push steps run.
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'CI Safety Guard'
    entrypoint: 'bash'
    args:
      - -c
      - |
        set -e
        cd /workspace
        chmod +x /workspace/.cloudbuild/ci_safety_guard.sh
        bash /workspace/.cloudbuild/ci_safety_guard.sh
        echo "CI SAFETY GUARD PASSED"

        echo "CI SAFETY GUARD PASSED — proceeding to build"

        echo "=== CI SAFETY GUARD PASSED ==="

  # ------------------------------------------------------------
  # PHASE 2: BUILD STRATEGY ENGINE
  # ------------------------------------------------------------
  - id: Build strategy-engine
    name: gcr.io/cloud-builders/docker
    args:
      - build
      - -t
      - ${_REGION}-docker.pkg.dev/${_PROJECT}/${_REPO}/strategy-engine:${_TAG}
      - -f
      - infra/Dockerfile.strategy_engine
      - .

  - id: Push strategy-engine
    name: gcr.io/cloud-builders/docker
    args:
      - push
      - ${_REGION}-docker.pkg.dev/${_PROJECT}/${_REPO}/strategy-engine:${_TAG}

  # ------------------------------------------------------------
  # PHASE 3: BUILD MARKETDATA MCP SERVER
  # ------------------------------------------------------------
  - id: Build marketdata-mcp-server
    name: gcr.io/cloud-builders/docker
    args:
      - build
      - -t
      - ${_REGION}-docker.pkg.dev/${_PROJECT}/${_REPO}/marketdata-mcp-server:${_TAG}
      - -f
      - infra/Dockerfile.marketdata_mcp_server
      - .

  - id: Push marketdata-mcp-server
    name: gcr.io/cloud-builders/docker
    args:
      - push
      - ${_REGION}-docker.pkg.dev/${_PROJECT}/${_REPO}/marketdata-mcp-server:${_TAG}

images:
  - ${_REGION}-docker.pkg.dev/${_PROJECT}/${_REPO}/strategy-engine:${_TAG}
  - ${_REGION}-docker.pkg.dev/${_PROJECT}/${_REPO}/marketdata-mcp-server:${_TAG}
