# This CI pipeline enforces institutional safety guarantees.
steps:
  - name: 'gcr.io/cloud-builders/bash'
    id: 'Safety Guard'
    entrypoint: 'bash' # RISK: Assumes the container image has `bash` in PATH; if `name: bash` pulls a minimal image, this can be "exec: bash: not found".
    args:
      - '-c'
      - |
        set -euo pipefail

        # NOTE: This guard is intentionally explicit and chatty.
        # It should fail fast with actionable output when a safety invariant is violated.

        echo "--- Checking for ':latest' image tags ---"
        mapfile -t YAML_FILES < <(find . -type f \( -name "*.yaml" -o -name "*.yml" \) ! -name "cloudbuild*")
        if [ "${#YAML_FILES[@]}" -gt 0 ] && grep -nE "image:.*:latest\b" "${YAML_FILES[@]}"; then
          echo "❌ FAILED: Use of ':latest' image tag is forbidden."
          exit 1
        else
          echo "✅ PASSED: No ':latest' image tags found."
        fi

        echo "--- Checking for 'AGENT_MODE=EXECUTE' ---"
        mapfile -t CODE_FILES < <(find . -type f \( -name "*.yaml" -o -name "*.yml" -o -name "*.py" -o -name "*.sh" -o -name "Dockerfile" -o -name "Dockerfile.*" \) ! -name "cloudbuild*")
        if [ "${#CODE_FILES[@]}" -gt 0 ] && grep -nE "AGENT_MODE[[:space:]]*[:=][[:space:]]*(['\"])?EXECUTE\1" "${CODE_FILES[@]}" | grep -v "ALLOWED_AGENT_MODES"; then
          echo "❌ FAILED: AGENT_MODE must not be set to EXECUTE in committed code."
          exit 1
        else
          echo "✅ PASSED: No instances of 'AGENT_MODE=EXECUTE' found."
        fi

        echo "--- Checking for scaled execution agents (replicas > 0) ---"
        mapfile -t EXEC_AGENT_MANIFESTS < <(grep -rl --include="*.yaml" --include="*.yml" "name: execution-agent" ./k8s 2>/dev/null || true)
        SCALED_EXECUTION_AGENT=0
        for MANIFEST in "${EXEC_AGENT_MANIFESTS[@]}"; do
          if grep -nE "replicas:[[:space:]]*[1-9]" "$MANIFEST"; then
            SCALED_EXECUTION_AGENT=1
          fi
        done

        if [ "$SCALED_EXECUTION_AGENT" -eq 1 ]; then
          echo "❌ FAILED: Execution agent replicas must be 0 in committed code."
          exit 1
        fi
        echo "✅ PASSED: No execution agents found with replicas > 0."

  - name: 'python:3.11-slim'
    id: 'Smoke check Python imports (pre-docker)'
    entrypoint: 'bash'
    args: ["-c", "python scripts/smoke_check_imports.py"]

  # Build and push marketdata-mcp-server
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Build marketdata-mcp-server'
    args: [
      'build',
      '-t', '${_REGION}-docker.pkg.dev/${_PROJECT}/${_REPO}/marketdata-mcp-server:${_TAG}',
      '-f', '/workspace/backend/Dockerfile.marketdata-mcp-server',
      '/workspace'
    ]

  - name: 'gcr.io/cloud-builders/bash'
    id: 'Import gate marketdata-mcp-server'
    entrypoint: 'bash'
    args:
      - "-c"
      - |
        set -euo pipefail
        IMAGE_REF='${_REGION}-docker.pkg.dev/${_PROJECT}/${_REPO}/marketdata-mcp-server:${_TAG}'
        chmod +x ./scripts/ci_import_gate.sh
        ./scripts/ci_import_gate.sh "${IMAGE_REF}" backend.app

  # Build and push strategy-engine
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Build strategy-engine'
    args: [
      'build',
      '-t', '${_REGION}-docker.pkg.dev/${_PROJECT}/${_REPO}/strategy-engine:${_TAG}',
      '-f', '/workspace/infra/Dockerfile.strategy_engine',
      '/workspace'
    ]

  - name: 'gcr.io/cloud-builders/bash'
    id: 'Import gate strategy-engine'
    entrypoint: 'bash'
    args:
      - "-c"
      - |
        set -euo pipefail
        IMAGE_REF='${_REGION}-docker.pkg.dev/${_PROJECT}/${_REPO}/strategy-engine:${_TAG}'
        chmod +x ./scripts/ci_import_gate.sh
        ./scripts/ci_import_gate.sh "${IMAGE_REF}" backend.strategy_engine.service

  # Build and push strategy-runtime (used by gamma and whale strategies)
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Build strategy-runtime'
    args: [
      'build',
      '-t', '${_REGION}-docker.pkg.dev/${_PROJECT}/${_REPO}/strategy-runtime:${_TAG}',
      '-f', '/workspace/backend/strategy_service/Dockerfile',
      '/workspace'
    ]

  - name: 'gcr.io/cloud-builders/bash'
    id: 'Import gate strategy-runtime'
    entrypoint: 'bash'
    args:
      - "-c"
      - |
        set -euo pipefail
        IMAGE_REF='${_REGION}-docker.pkg.dev/${_PROJECT}/${_REPO}/strategy-runtime:${_TAG}'
        chmod +x ./scripts/ci_import_gate.sh
        ./scripts/ci_import_gate.sh "${IMAGE_REF}" backend.strategy_service.app
