# This CI pipeline enforces institutional safety guarantees.
steps:
  - name: gcr.io/cloud-builders/gcloud
    id: preflight
    entrypoint: bash
    args:
      - -c
      - |
        set -euo pipefail
        pwd
        ls -la
        ls -la /workspace
        ls -la /workspace/scripts || true
        echo "BRANCH=$BRANCH_NAME COMMIT=$COMMIT_SHA" || true

  - name: gcr.io/cloud-builders/gcloud
    id: Safety Guard
    entrypoint: bash
    args:
      - -c
      - |
        set -euo pipefail
        test -f /workspace/scripts/ci_safety_guard.sh
        ls -la /workspace/scripts/ci_safety_guard.sh
        chmod +x /workspace/scripts/ci_safety_guard.sh
        /workspace/scripts/ci_safety_guard.sh
        echo "✅ SAFETY GUARD PASS"

  - name: 'python:3.11-slim'
    id: 'Smoke check Python imports (pre-docker)'
    entrypoint: 'bash'
    args: ["-c", "python scripts/smoke_check_imports.py"]

  # Build and push marketdata-mcp-server
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Build marketdata-mcp-server'
    args: [
      'build',
      '-t', '${_REGION}-docker.pkg.dev/${_PROJECT}/${_REPO}/marketdata-mcp-server:${_TAG}',
      '-f', '/workspace/backend/Dockerfile.marketdata-mcp-server',
      '/workspace'
    ]

  - name: 'gcr.io/cloud-builders/bash'
    id: 'Import gate marketdata-mcp-server'
    entrypoint: 'bash'
    args:
      - "-c"
      - |
        set -euo pipefail
        IMAGE_REF='${_REGION}-docker.pkg.dev/${_PROJECT}/${_REPO}/marketdata-mcp-server:${_TAG}'
        chmod +x ./scripts/ci_import_gate.sh
        ./scripts/ci_import_gate.sh "${IMAGE_REF}" backend.app

  # Build and push strategy-engine
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Build strategy-engine'
    args: [
      'build',
      '-t', '${_REGION}-docker.pkg.dev/${_PROJECT}/${_REPO}/strategy-engine:${_TAG}',
      '-f', '/workspace/infra/Dockerfile.strategy_engine',
      '/workspace'
    ]

  - name: 'gcr.io/cloud-builders/bash'
    id: 'Import gate strategy-engine'
    entrypoint: 'bash'
    args:
      - "-c"
      - |
        set -euo pipefail
        IMAGE_REF='${_REGION}-docker.pkg.dev/${_PROJECT}/${_REPO}/strategy-engine:${_TAG}'
        chmod +x ./scripts/ci_import_gate.sh
        ./scripts/ci_import_gate.sh "${IMAGE_REF}" backend.strategy_engine.service

  # Build and push strategy-runtime (used by gamma and whale strategies)
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Build strategy-runtime'
    args: [
      'build',
      '-t', '${_REGION}-docker.pkg.dev/${_PROJECT}/${_REPO}/strategy-runtime:${_TAG}',
      '-f', '/workspace/backend/strategy_service/Dockerfile',
      '/workspace'
    ]

  - name: 'gcr.io/cloud-builders/bash'
    id: 'Import gate strategy-runtime'
    entrypoint: 'bash'
    args:
      - "-c"
      - |
        set -euo pipefail
        IMAGE_REF='${_REGION}-docker.pkg.dev/${_PROJECT}/${_REPO}/strategy-runtime:${_TAG}'
        chmod +x ./scripts/ci_import_gate.sh
        ./scripts/ci_import_gate.sh "${IMAGE_REF}" backend.strategy_service.app
