timeout: 3600s

  # a) Checkout
  - name: 'gcr.io/cloud-builders/git'
    id: 'Checkout'
    entrypoint: 'bash'
    args:
      - -c
      - |
        set -euo pipefail
        echo "--- Checkout / source context ---"
        echo "PWD=$$(pwd)"
        echo "Workspace contents:"
        ls -la
        if [ -d .git ]; then
          echo "GIT_SHA=$$(git rev-parse HEAD)"
          echo "GIT_STATUS_PORCELAIN:"
          git status --porcelain || true
        else
          echo "INFO: .git directory not present (source may be provided as an archive)."
        fi

  # b) Safety guard
  - name: 'gcr.io/cloud-builders/bash'
    id: 'CI Layout Validate'
    waitFor: ['Checkout']
    entrypoint: 'bash'
    args:
      - -c
      - |
        set -euo pipefail
        bash ./scripts/validate_ci_layout.sh

  - name: 'gcr.io/cloud-builders/bash'
    id: 'Safety Guard'
    entrypoint: 'bash'
    args:
      - -c
      - |
        set -euo pipefail
        echo "--- Safety Guard preflight ---"
        chmod +x ./scripts/ci_safety_guard.sh
        ./scripts/ci_safety_guard.sh
    waitFor: ['CI Layout Validate']

  # c) Import smoke check (source-based; fail fast before image builds).
  #
  # We intentionally install from a pinned lock file for deterministic results.
  # The smoke check here is scoped to the entrypoints built in this pipeline.
  - name: 'python:3.12-slim'
    id: 'Import smoke check'
    waitFor: ['Safety Guard']
    entrypoint: 'bash'
    args:
      - -c
      - |
        set -euo pipefail
        echo "--- Import smoke check (source) ---"
        python -V
        python -m pip --version || python -m ensurepip
        python -m pip install --no-cache-dir --upgrade pip
        python -m pip install --no-cache-dir -r backend/strategy_service/requirements.lock
        python ./scripts/smoke_check_imports.py \
          --no-defaults \
          --module backend.app \
          --module backend.strategy_engine.service \
          --module backend.strategy_service.app

  # ------------------------------------------------------------
  # PHASE 2: BUILD STRATEGY ENGINE
  # ------------------------------------------------------------
  - id: Build strategy-engine
    name: gcr.io/cloud-builders/docker
    args:
      - build
      - -t
      - ${_REGION}-docker.pkg.dev/${_PROJECT}/${_REPO}/strategy-engine:${_TAG}
      - -f
      - infra/Dockerfile.strategy_engine
      - .

  - id: Push strategy-engine
    name: gcr.io/cloud-builders/docker
    args:
      - push
      - ${_REGION}-docker.pkg.dev/${_PROJECT}/${_REPO}/strategy-engine:${_TAG}

  # ------------------------------------------------------------
  # PHASE 3: BUILD MARKETDATA MCP SERVER
  # ------------------------------------------------------------
  - id: Build marketdata-mcp-server
    name: gcr.io/cloud-builders/docker
    args:
      - build
      - -t
      - ${_REGION}-docker.pkg.dev/${_PROJECT}/${_REPO}/marketdata-mcp-server:${_TAG}
      - -f
      - infra/Dockerfile.marketdata_mcp_server
      - .

  - id: Push marketdata-mcp-server
    name: gcr.io/cloud-builders/docker
    args:
      - push
      - ${_REGION}-docker.pkg.dev/${_PROJECT}/${_REPO}/marketdata-mcp-server:${_TAG}

images:
  - ${_REGION}-docker.pkg.dev/${_PROJECT}/${_REPO}/strategy-engine:${_TAG}
  - ${_REGION}-docker.pkg.dev/${_PROJECT}/${_REPO}/marketdata-mcp-server:${_TAG}
