steps:
  - name: 'bash'
    id: 'Copy Safety Guard Script'
    entrypoint: 'bash'
    args:
      - '-c'
      - 'cp ./scripts/ci_safety_guard.sh /workspace/ci_safety_guard.sh && chmod +x /workspace/ci_safety_guard.sh'

  - name: 'bash'
    id: 'Safety Guard'
    entrypoint: '/workspace/ci_safety_guard.sh'

  # Build and push marketdata-mcp-server
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Build marketdata-mcp-server'
    args: [
      'build',
      '-t', '${_REGION}-docker.pkg.dev/${_PROJECT}/${_REPO}/marketdata-mcp-server:${_TAG}',
      '-f', 'backend/Dockerfile.marketdata-mcp-server',
      '.'
    ]

  # Build and push strategy-engine
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Build strategy-engine'
    args: [
      'build',
      '-t', '${_REGION}-docker.pkg.dev/${_PROJECT}/${_REPO}/strategy-engine:${_TAG}',
      '-f', 'infra/Dockerfile.strategy_engine',
      '.'
    ]

  # Build and push strategy-runtime (used by gamma and whale strategies)
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Build strategy-runtime'
    args: [
      'build',
      '-t', '${_REGION}-docker.pkg.dev/${_PROJECT}/${_REPO}/strategy-runtime:${_TAG}',
      '-f', 'backend/strategy_service/Dockerfile',
      '.'
    ]

  # Build and push congressional-ingest
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Build congressional-ingest'
    args: [
      'build',
      '-t', '${_REGION}-docker.pkg.dev/${_PROJECT}/${_REPO}/congressional-ingest:${_TAG}',
      '-f', 'backend/ingestion/congressional/Dockerfile',
      '.'
    ]