steps:
  - name: 'bash'
    id: 'Safety Guard'
    entrypoint: '/bin/sh'
    args:
      - '-c'
      - './scripts/ci_safety_guard.sh'
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'build',
    '-t', '${_REGION}-docker.pkg.dev/${_PROJECT}/${_REPO}/marketdata-mcp-server:${_TAG}',
    '-f', 'backend/Dockerfile.marketdata-mcp-server',
    '.'
  ]
images:
- '${_REGION}-docker.pkg.dev/${_PROJECT}/${_REPO}/marketdata-mcp-server:${_TAG}'