timeout: 3600s

  # a) Checkout
  - name: 'gcr.io/cloud-builders/git'
    id: 'Checkout'
    entrypoint: 'bash'
    args:
      - -ceu
      - |
        echo "================================================================"
        echo "PHASE 1: preflight"
        echo "================================================================"
        echo "--- Checkout / source context ---"
        echo "PWD=$$(pwd)"
        echo "Workspace contents:"
        ls -la
        if [ -d .git ]; then
          echo "GIT_SHA=$$(git rev-parse HEAD)"
          echo "GIT_STATUS_PORCELAIN:"
          git status --porcelain || true
        else
          echo "INFO: .git directory not present (source may be provided as an archive)."
        fi

  # b) Safety guard
  - name: 'gcr.io/cloud-builders/bash'
    id: 'CI Layout Validate'
    entrypoint: 'bash'
    args:
      - -ceu
      - |
        echo "---- preflight: CI layout validate ----"
        bash ./scripts/validate_ci_layout.sh

  - name: 'bash'
    id: 'Safety Guard'
    waitFor: ['Checkout']
    entrypoint: 'bash'
    args:
      - -c
      - |
        set -euo pipefail

        echo "================================================================"
        echo "PHASE 2: safety guard"
        echo "================================================================"
        echo "--- Safety Guard preflight ---"
        echo "PWD: $(pwd)"

        # Diagnostics for unexpected tool/runtime issues.
        diag_grep_error() {
          local check_name="$1"
          local files_count="$2"
          echo "----- Debug: ${check_name} (grep error) -----" >&2
          echo "PWD: $(pwd)" >&2
          echo "WORKSPACE_ROOT: ${WORKSPACE_ROOT:-<unset>}" >&2
          echo "Files scanned: ${files_count}" >&2
          echo "Listing PWD:" >&2
          ls -la >&2 || true
          echo "----- End Debug -----" >&2
        }

        # Run grep against an explicit file list, interpreting exit codes robustly:
        # - 0 => policy violation (FAIL with exit 1) and print offending lines
        # - 1 => PASS (no matches)
        # - 2 => grep/runtime error (FAIL with exit 1) and print diagnostics
        #
        # Usage:
        #   run_grep_check "<check name>" "<fail message>" "<grep regex>" <file1> <file2> ...
        run_grep_check() {
          local check_name="$1"
          local fail_message="$2"
          local grep_pattern="$3"
          shift 3
          local -a files=( "$@" )

          echo "--- ${check_name} ---"
          echo "Files scanned: ${#files[@]}"
          if ((${#files[@]} == 0)); then
            echo "✅ PASSED: No files to scan."
            return 0
          fi

          set +e
          local matches
          matches="$(grep -nH "${grep_pattern}" -- "${files[@]}" 2>&1)"
          local rc=$?
          set -e

          if [[ ${rc} -eq 0 ]]; then
            echo "❌ FAILED: ${fail_message}"
            echo "${matches}"
            exit 1
          else
            echo "✅ PASSED: No ':latest' image tags found."
          fi
        fi

        # ----------------------------
        # Rule 2: No AGENT_MODE=EXECUTE
        # ----------------------------
        echo "--- Rule: forbid AGENT_MODE=EXECUTE ---"
        FILES=$(find . -type f \( -name "*.yaml" -o -name "*.yml" -o -name "*.py" -o -name "*.sh" -o -name "Dockerfile" \) ! -name "cloudbuild.yaml" || true)
        if [ -z "$FILES" ]; then
          echo "No relevant files found (PASS)"
        else
          if echo "$FILES" | xargs -r grep -nE "AGENT_MODE\s*[:=]\s*EXECUTE"; then
            echo "❌ FAILED: AGENT_MODE=EXECUTE is forbidden in committed code."
            exit 1
          else
            echo "✅ PASSED: No AGENT_MODE=EXECUTE found."
          fi
        fi

        # ----------------------------
        # Rule 3: Execution agents must not be scaled
        # ----------------------------
        echo "--- Rule: execution agents replicas must be 0 ---"
        if [ -d "./k8s/execution" ]; then
          if grep -R "replicas:[[:space:]]*[1-9]" ./k8s/execution; then
            echo "❌ FAILED: Execution agents must have replicas: 0."
            exit 1
          else
            echo "✅ PASSED: Execution agents not scaled."
          fi
        else
          echo "No execution manifests present (PASS)"
        fi

  # c) Import smoke check (source-based; fail fast before image builds).
  #
  # We intentionally install from a pinned lock file for deterministic results.
  # The smoke check here is scoped to the entrypoints built in this pipeline.
  - name: 'python:3.12-slim'
    id: 'Import smoke check'
    waitFor: ['Safety Guard']
    entrypoint: 'bash'
    args:
      - -ceu
      - |
        echo "================================================================"
        echo "PHASE 3: import smoke"
        echo "================================================================"
        echo "--- Import smoke check (source) ---"
        python -V
        python -m pip --version || python -m ensurepip
        python -m pip install --no-cache-dir --upgrade pip
        python -m pip install --no-cache-dir -r backend/strategy_service/requirements.lock
        python ./scripts/smoke_check_imports.py \
          --no-defaults \
          --module backend.app \
          --module backend.strategy_engine.service \
          --module backend.strategy_service.app

  # d) Docker build(s) (serialized; each build is immediately gated).
  #
  # NOTE: The "import gate" runs inside the built image (docker run) to validate
  # runtime imports using the image's own dependency set.

  - name: 'gcr.io/cloud-builders/bash'
    id: 'PHASE 4: docker build'
    waitFor: ['Import smoke check']
    entrypoint: 'bash'
    args:
      - -ceu
      - |
        echo "================================================================"
        echo "PHASE 4: docker build"
        echo "================================================================"

  # Build marketdata-mcp-server
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Build marketdata-mcp-server'
    waitFor: ['PHASE 4: docker build']
    args: [
      'build',
      '-t', '${_REGION}-docker.pkg.dev/${_PROJECT}/${_REPO}/marketdata-mcp-server:${_TAG}',
      '-f', '/workspace/backend/Dockerfile.marketdata-mcp-server',
      '/workspace'
    ]

  - name: 'gcr.io/cloud-builders/bash'
    id: 'Import gate marketdata-mcp-server'
    waitFor: ['Build marketdata-mcp-server']
    entrypoint: 'bash'
    args:
      - build
      - -t
      - ${_REGION}-docker.pkg.dev/${_PROJECT}/${_REPO}/strategy-engine:${_TAG}
      - -f
      - infra/Dockerfile.strategy_engine
      - .

  - id: Push strategy-engine
    name: gcr.io/cloud-builders/docker
    args:
      - push
      - ${_REGION}-docker.pkg.dev/${_PROJECT}/${_REPO}/strategy-engine:${_TAG}

  # ------------------------------------------------------------
  # PHASE 3: BUILD MARKETDATA MCP SERVER
  # ------------------------------------------------------------
  - id: Build marketdata-mcp-server
    name: gcr.io/cloud-builders/docker
    args:
      - "-c"
      - |
        set -euo pipefail
        IMAGE_REF='${_REGION}-docker.pkg.dev/${_PROJECT}/${_REPO}/strategy-runtime:${_TAG}'
        sh ./scripts/ci_import_gate.sh "${IMAGE_REF}" backend.strategy_service.app

  # e) Docker push(es) (serialized; publish only after all gates pass).
  - name: 'gcr.io/cloud-builders/bash'
    id: 'PHASE 5: docker push'
    waitFor: ['Import gate strategy-runtime']
    entrypoint: 'bash'
    args:
      - -ceu
      - |
        echo "================================================================"
        echo "PHASE 5: docker push"
        echo "================================================================"

  - name: 'gcr.io/cloud-builders/docker'
    id: 'Push marketdata-mcp-server'
    waitFor: ['PHASE 5: docker push']
    args: [
      'push',
      '${_REGION}-docker.pkg.dev/${_PROJECT}/${_REPO}/marketdata-mcp-server:${_TAG}'
    ]

  - name: 'gcr.io/cloud-builders/docker'
    id: 'Push strategy-engine'
    waitFor: ['Push marketdata-mcp-server']
    args: [
      'push',
      '${_REGION}-docker.pkg.dev/${_PROJECT}/${_REPO}/strategy-engine:${_TAG}'
    ]

images:
  - ${_REGION}-docker.pkg.dev/${_PROJECT}/${_REPO}/strategy-engine:${_TAG}
  - ${_REGION}-docker.pkg.dev/${_PROJECT}/${_REPO}/marketdata-mcp-server:${_TAG}
