timeout: 3600s

substitutions:
  _PROJECT: agenttrader-prod
  _REGION: us-east4
  _REPO: trader-repo
  _TAG: ${SHORT_SHA}

steps:
  # ------------------------------------------------------------
  # PHASE 1: SAFETY GUARD (DETERMINISTIC, HARDENED)
  # ------------------------------------------------------------
  - id: Safety Guard
    name: bash
    entrypoint: bash
    args:
      - -c
      - |
        set -euo pipefail

        echo "=== CI SAFETY GUARD START ==="
        ROOT="$(pwd)"
        echo "Repo root: $ROOT"

        # ----------------------------
        # Rule 1: No :latest images
        # ----------------------------
        echo "--- Rule: forbid :latest image tags ---"
        FILES=$(find . -type f \( -name "*.yaml" -o -name "*.yml" \) ! -name "cloudbuild.yaml" || true)
        if [ -z "$FILES" ]; then
          echo "No YAML files found (PASS)"
        else
          if echo "$FILES" | xargs -r grep -n "image:.*:latest"; then
            echo "❌ FAILED: ':latest' image tags are forbidden."
            exit 1
          else
            echo "✅ PASSED: No ':latest' image tags found."
          fi
        fi

        # ----------------------------
        # Rule 2: No AGENT_MODE=EXECUTE
        # ----------------------------
        echo "--- Rule: forbid AGENT_MODE=EXECUTE ---"
        FILES=$(find . -type f \( -name "*.yaml" -o -name "*.yml" -o -name "*.py" -o -name "*.sh" -o -name "Dockerfile" \) ! -name "cloudbuild.yaml" || true)
        if [ -z "$FILES" ]; then
          echo "No relevant files found (PASS)"
        else
          if echo "$FILES" | xargs -r grep -nE "AGENT_MODE\s*[:=]\s*EXECUTE"; then
            echo "❌ FAILED: AGENT_MODE=EXECUTE is forbidden in committed code."
            exit 1
          else
            echo "✅ PASSED: No AGENT_MODE=EXECUTE found."
          fi
        fi

        # ----------------------------
        # Rule 3: Execution agents must not be scaled
        # ----------------------------
        echo "--- Rule: execution agents replicas must be 0 ---"
        if [ -d "./k8s/execution" ]; then
          if grep -R "replicas:[[:space:]]*[1-9]" ./k8s/execution; then
            echo "❌ FAILED: Execution agents must have replicas: 0."
            exit 1
          else
            echo "✅ PASSED: Execution agents not scaled."
          fi
        else
          echo "No execution manifests present (PASS)"
        fi

        echo "=== CI SAFETY GUARD PASSED ==="

  # ------------------------------------------------------------
  # PHASE 2: BUILD STRATEGY ENGINE
  # ------------------------------------------------------------
  - id: Build strategy-engine
    name: gcr.io/cloud-builders/docker
    args:
      - build
      - -t
      - ${_REGION}-docker.pkg.dev/${_PROJECT}/${_REPO}/strategy-engine:${_TAG}
      - -f
      - infra/Dockerfile.strategy_engine
      - .

  - id: Push strategy-engine
    name: gcr.io/cloud-builders/docker
    args:
      - push
      - ${_REGION}-docker.pkg.dev/${_PROJECT}/${_REPO}/strategy-engine:${_TAG}

  # ------------------------------------------------------------
  # PHASE 3: BUILD MARKETDATA MCP SERVER
  # ------------------------------------------------------------
  - id: Build marketdata-mcp-server
    name: gcr.io/cloud-builders/docker
    args:
      - build
      - -t
      - ${_REGION}-docker.pkg.dev/${_PROJECT}/${_REPO}/marketdata-mcp-server:${_TAG}
      - -f
      - infra/Dockerfile.marketdata_mcp_server
      - .

  - id: Push marketdata-mcp-server
    name: gcr.io/cloud-builders/docker
    args:
      - push
      - ${_REGION}-docker.pkg.dev/${_PROJECT}/${_REPO}/marketdata-mcp-server:${_TAG}

images:
  - ${_REGION}-docker.pkg.dev/${_PROJECT}/${_REPO}/strategy-engine:${_TAG}
  - ${_REGION}-docker.pkg.dev/${_PROJECT}/${_REPO}/marketdata-mcp-server:${_TAG}
