# This CI pipeline enforces institutional safety guarantees.
#
# Contract:
# - CI safety guard must run and pass before any docker build step.
# - No non-deterministic images (e.g. implicit :latest) may be referenced.
# - Only allowed Cloud Build substitutions are used: _PROJECT, _REGION, _REPO, _TAG, SHORT_SHA.
steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'Diagnostics (pre-build)'
    entrypoint: 'bash'
    args:
      - -ceu
      - |
        echo "================================================================"
        echo "PHASE 1: preflight"
        echo "================================================================"
        echo "--- Source context ---"
        echo "PWD=$$(pwd)"
        echo "Workspace contents:"
        ls -la
        ls -la scripts/ || true
        git rev-parse --short HEAD || true
        echo "$$BRANCH_NAME $$COMMIT_SHA" || true

  - name: 'gcr.io/cloud-builders/bash'
    id: 'CI Layout Validate'
    waitFor: ['Diagnostics (pre-build)']
    entrypoint: 'bash'
    args:
      - -ceu
      - |
        echo "---- preflight: CI layout validate ----"
        bash ./scripts/validate_ci_layout.sh

  # Safety guard MUST pass before any docker build steps run.
  - name: 'gcr.io/cloud-builders/bash'
    id: 'CI Safety Guard'
    waitFor: ['CI Layout Validate']
    entrypoint: 'bash'
    args:
      - -ceu
      - |
        chmod +x ./scripts/ci_safety_guard.sh
        ./scripts/ci_safety_guard.sh
        echo "CI SAFETY GUARD PASSED — proceeding to build"

  # Import smoke check (source-based; fail fast before image builds).
  - name: 'python:3.12-slim'
    id: 'Import smoke check'
    waitFor: ['CI Safety Guard']
    entrypoint: 'bash'
    args:
      - -ceu
      - |
        echo "================================================================"
        echo "PHASE 2: import smoke"
        echo "================================================================"
        python -V
        python -m pip install --no-cache-dir --upgrade pip
        python -m pip install --no-cache-dir -r backend/strategy_service/requirements.lock
        python ./scripts/smoke_check_imports.py \\
          --no-defaults \\
          --module backend.app \\
          --module backend.strategy_engine.service \\
          --module backend.strategy_service.app

  # Build + gate: marketdata-mcp-server
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Build marketdata-mcp-server'
    waitFor: ['Import smoke check']
    args: [
      'build',
      '-t', '${_REGION}-docker.pkg.dev/${_PROJECT}/${_REPO}/marketdata-mcp-server:${_TAG}',
      '-f', 'backend/Dockerfile.marketdata-mcp-server',
      '.'
    ]

  - name: 'gcr.io/cloud-builders/bash'
    id: 'Import gate marketdata-mcp-server'
    waitFor: ['Build marketdata-mcp-server']
    entrypoint: 'bash'
    args:
      - '-ceu'
      - |
        IMAGE_REF='${_REGION}-docker.pkg.dev/${_PROJECT}/${_REPO}/marketdata-mcp-server:${_TAG}'
        chmod +x ./scripts/ci_import_gate.sh
        ./scripts/ci_import_gate.sh "$$IMAGE_REF" backend.app

  # Build + gate: strategy-engine
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Build strategy-engine'
    waitFor: ['Import gate marketdata-mcp-server']
    args: [
      'build',
      '-t', '${_REGION}-docker.pkg.dev/${_PROJECT}/${_REPO}/strategy-engine:${_TAG}',
      '-f', 'infra/Dockerfile.strategy_engine',
      '.'
    ]

  - name: 'gcr.io/cloud-builders/bash'
    id: 'Import gate strategy-engine'
    waitFor: ['Build strategy-engine']
    entrypoint: 'bash'
    args:
      - '-ceu'
      - |
        IMAGE_REF='${_REGION}-docker.pkg.dev/${_PROJECT}/${_REPO}/strategy-engine:${_TAG}'
        chmod +x ./scripts/ci_import_gate.sh
        ./scripts/ci_import_gate.sh "$$IMAGE_REF" backend.strategy_engine.service

images:
  - '${_REGION}-docker.pkg.dev/${_PROJECT}/${_REPO}/marketdata-mcp-server:${_TAG}'
  - '${_REGION}-docker.pkg.dev/${_PROJECT}/${_REPO}/strategy-engine:${_TAG}'
