steps:
  - name: 'gcr.io/cloud-builders/bash'
    id: 'Safety Guard'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        set -euo pipefail
        chmod +x ./scripts/ci_safety_guard.sh
        ./scripts/ci_safety_guard.sh
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Build marketdata-mcp-server'
    waitFor: ['Safety Guard']
    args:
      - build
      - -t
      - ${_REGION}-docker.pkg.dev/${_PROJECT}/${_REPO}/marketdata-mcp-server:${_TAG}
      - -f
      - backend/Dockerfile.marketdata-mcp-server
      - .

  - name: 'gcr.io/cloud-builders/bash'
    id: 'Import gate marketdata-mcp-server'
    waitFor: ['Build marketdata-mcp-server']
    entrypoint: 'bash'
    args:
      - "-c"
      - |
        set -euo pipefail
        IMAGE_REF='${_REGION}-docker.pkg.dev/${_PROJECT}/${_REPO}/marketdata-mcp-server:${_TAG}'
        chmod +x ./scripts/ci_import_gate.sh
        ./scripts/ci_import_gate.sh "$${IMAGE_REF}" backend.app
images:
  - ${_REGION}-docker.pkg.dev/${_PROJECT}/${_REPO}/marketdata-mcp-server:${_TAG}
