# Cloud Build configuration for Congressional Disclosure Ingestion service

steps:
  # Build the Docker image (deployment is handled via Kubernetes in us-east4).
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-f'
      - 'infra/Dockerfile.congressional_ingest'
      - '-t'
      - 'us-east4-docker.pkg.dev/agenttrader-prod/trader-repo/congressional-ingest:$SHORT_SHA'
      - '-t'
      - 'us-east4-docker.pkg.dev/agenttrader-prod/trader-repo/congressional-ingest:latest'
      - '.'
    id: 'build-image'

# Substitution variables (can be overridden at build time)
substitutions:
  _TENANT_ID: 'prod'
  _NATS_URL: 'nats://nats-service.prod:4222'
  _POLL_INTERVAL_SECONDS: '3600'
  _LOOKBACK_DAYS: '7'

# Image outputs
images:
  - 'us-east4-docker.pkg.dev/agenttrader-prod/trader-repo/congressional-ingest:$SHORT_SHA'
  - 'us-east4-docker.pkg.dev/agenttrader-prod/trader-repo/congressional-ingest:latest'

# Build options
options:
  machineType: 'N1_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY

timeout: '1200s'
