# Cloud Build configuration for Congressional Disclosure Ingestion service

steps:
  - name: gcr.io/cloud-builders/bash
    id: 'Safety Guard'
    entrypoint: bash
    args:
      - "-c"
      - |
        set -euo pipefail
        chmod +x ./scripts/ci_safety_guard.sh
        ./scripts/ci_safety_guard.sh
  # Capture a deterministic UTC build timestamp for downstream steps.
  - name: gcr.io/cloud-builders/bash
    id: 'capture-build-time'
    entrypoint: bash
    waitFor: ['Safety Guard']
    args:
      - -c
      - |
        set -euo pipefail
        date -u +%Y-%m-%dT%H:%M:%SZ > /workspace/.build_time_utc

  # Build the Docker image (deployment is handled via Kubernetes in us-east4).
  - name: gcr.io/cloud-builders/bash
    entrypoint: bash
    waitFor: ['capture-build-time']
    args:
      - -c
      - |
        set -euo pipefail
        BUILD_TIME_UTC="$(cat /workspace/.build_time_utc)"
        GIT_SHA="${COMMIT_SHA:-$SHORT_SHA}"
        IMAGE_REF="gcr.io/$PROJECT_ID/congressional-ingest:$SHORT_SHA"
        docker build \
          -f infra/Dockerfile.congressional_ingest \
          --build-arg GIT_SHA="${GIT_SHA}" \
          --build-arg BUILD_ID="${BUILD_ID}" \
          --build-arg BUILD_TIME_UTC="${BUILD_TIME_UTC}" \
          --build-arg IMAGE_REF="${IMAGE_REF}" \
          -t "${IMAGE_REF}" \
          .
    id: 'build-image'

  # Build-time import gate: fail fast if entrypoint imports are broken.
  - name: gcr.io/cloud-builders/bash
    entrypoint: bash
    waitFor: ['build-image']
    args:
      - "-c"
      - |
        set -euo pipefail
        IMAGE_REF="gcr.io/$PROJECT_ID/congressional-ingest:$SHORT_SHA"
        chmod +x ./scripts/ci_import_gate.sh
        ./scripts/ci_import_gate.sh "${IMAGE_REF}" backend.ingestion.congressional_disclosures
    id: 'import-gate'

  # Push the image to GCR
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/congressional-ingest:$SHORT_SHA'
    waitFor: ['import-gate']
    id: 'push-image-sha'

  # Deploy to Cloud Run
  - name: gcr.io/cloud-builders/bash
    entrypoint: bash
    waitFor: ['push-image-sha']
    args:
      - -c
      - |
        set -euo pipefail
        BUILD_TIME_UTC="$(cat /workspace/.build_time_utc)"
        GIT_SHA="${COMMIT_SHA:-$SHORT_SHA}"
        IMAGE_REF="gcr.io/$PROJECT_ID/congressional-ingest:$SHORT_SHA"
        gcloud run deploy congressional-ingest \
          --image="${IMAGE_REF}" \
          --platform=managed \
          --region=us-central1 \
          --set-env-vars="TENANT_ID=${_TENANT_ID}" \
          --set-env-vars="NATS_URL=${_NATS_URL}" \
          --set-env-vars="POLL_INTERVAL_SECONDS=${_POLL_INTERVAL_SECONDS}" \
          --set-env-vars="LOOKBACK_DAYS=${_LOOKBACK_DAYS}" \
          --set-env-vars="GIT_SHA=${GIT_SHA}" \
          --set-env-vars="BUILD_ID=${BUILD_ID}" \
          --set-env-vars="BUILD_TIME_UTC=${BUILD_TIME_UTC}" \
          --set-env-vars="IMAGE_REF=${IMAGE_REF}" \
          --update-secrets=QUIVER_API_KEY=quiver-api-key:latest \
          --cpu=1 \
          --memory=512Mi \
          --min-instances=1 \
          --max-instances=1 \
          --timeout=3600 \
          --no-cpu-throttling \
          --no-allow-unauthenticated
    id: 'deploy-cloud-run'

# Substitution variables (can be overridden at build time)
substitutions:
  _TENANT_ID: 'prod'
  _NATS_URL: 'nats://nats-service.prod:4222'
  _POLL_INTERVAL_SECONDS: '3600'
  _LOOKBACK_DAYS: '7'

# Image outputs
images:
  - 'gcr.io/$PROJECT_ID/congressional-ingest:$SHORT_SHA'

# Build options
options:
  machineType: 'N1_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY

timeout: '1200s'
