steps:
- name: 'gcr.io/cloud-builders/docker'
  args:
    [
      'build',
      '-t', 'us-east4-docker.pkg.dev/agenttrader-prod/trader-repo/agenttrader-stream-bridge:${SHORT_SHA}',
      '-t', 'us-east4-docker.pkg.dev/agenttrader-prod/trader-repo/agenttrader-stream-bridge:latest',
      '.',
      '-f', 'infra/Dockerfile.stream_bridge'
    ]
images:
- 'us-east4-docker.pkg.dev/agenttrader-prod/trader-repo/agenttrader-stream-bridge:${SHORT_SHA}'
- 'us-east4-docker.pkg.dev/agenttrader-prod/trader-repo/agenttrader-stream-bridge:latest'
