apiVersion: monitoring.googleapis.com/v1
kind: PodMonitoring
metadata:
  name: marketdata-mcp-server
spec:
  selector:
    matchLabels:
      app: marketdata-mcp-server
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
