apiVersion: monitoring.googleapis.com/v1
kind: PodMonitoring
metadata:
  name: whale-strategy
spec:
  selector:
    matchLabels:
      strategy: whale
  endpoints:
    - port: http
      path: /metrics
      interval: 30s

